name: Build and Push Docker Image

on:
  push:
    branches:
      - main        # 推送到 main 分支时触发
  workflow_dispatch: # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 拉取仓库代码
      - name: Checkout
        uses: actions/checkout@v4

      # 登录 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 设置 buildx（支持多平台）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 构建并推送
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./tg_bot_searcher        # 构建上下文（包含源码）
          file: ./tg_bot_searcher/Dockerfile # Dockerfile 路径
          push: true
          tags: |
            yourname/tg-bot-searcher:latest
            yourname/tg-bot-searcher:${{ github.sha }}
